### ISSUE TITLE
Incorrect Dialog Appears Instead of 404 Error for Random URL Path

### ISSUE THREAD

**Issue by sercanumit** [that-one-arab/quiz-buddy#1]
**Description of the Bug**
When navigating to a random, non-existent URL path, instead of receiving a 404 error page, a dialog box with misconfigured text and a request for an API key appears.

**Steps to Reproduce**
To reproduce this behavior, follow these steps:
1. Go to the application URL.
2. Enter a random or non-existent path (e.g., `https://quiz-buddy.xyz/not-exist`).
3. You will see the dialog box appear before a 404 error page.

**Expected Behavior**
This dialog box should not be displayed.

**Screenshots**
![dialog-error](https://github.com/user-attachments/assets/13b12823-f6b1-4218-93db-a8beab030316)

**Additional Context**
I might be encountering this error because I am using the application without entering an API key, but I am not sure.

**Comment by that-one-arab** [comment]
Great catch! This is a bug related to the **Welcome Dialog** displaying on all routes, instead of just valid routes.
