### ISSUE TITLE
Provide a docker compose to get started

### ISSUE THREAD

**Issue by arsaboo** [that-one-arab/quiz-buddy#4]
Please provide a docker compose to get started...thanks🙏

**Comment by that-one-arab** [comment]
Hey @arsaboo! This is actually on my list of priorities, but for now you can try running the project locally by following the README instructions in the Frontend and Backend directories. Let me know if you have any issues!

**Comment by arsaboo** [comment]
Thanks, @that-one-arab. I am hoping you get to it soon. I will wait until then...
