### ISSUE TITLE
[Error: ENOENT: no such file or directory, open '/home/ubuntu/quiz-buddy/frontend/.next/BUILD_ID']

### ISSUE THREAD

**Issue by mattodinaturas** [that-one-arab/quiz-buddy#6]
Hi, i'm opening another issue, this time related to frontend. after performing `npm install` i try to execture `npm start` but i get this error:

```
ubuntu@instance-20240904-1203:~/quiz-buddy/frontend$ sudo npm start

> exam-buddy@0.1.0 start
> next start

   ▲ Next.js 14.1.0
   - Local:        http://localhost:3000

[Error: ENOENT: no such file or directory, open '/home/ubuntu/quiz-buddy/frontend/.next/BUILD_ID'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/ubuntu/quiz-buddy/frontend/.next/BUILD_ID'
}
ubuntu@instance-20240904-1203:~/quiz-buddy/frontend$ 


```

am i doing something wrong? thanks

**Comment by that-one-arab** [comment]
`npm start` needs a build for it to start, you can run `npm run build` first, or you can directly run `npm run dev` for local development.
Inspect package.json and see nextjs docs for more info.

Let me know if you still have issues

**Comment by mattodinaturas** [comment]
hi, it worked with `npm run build` . Unfortunately instructions are not clear and it's not easy for a rookie like me to mathe this program work. Thanks

**Comment by that-one-arab** [comment]
Thats alright, closing this issue
