### ISSUE TITLE
NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by mattodinaturas** [that-one-arab/quiz-buddy#7]
Hi, i'm sorry but i continue to have issues with this program. I was able to get to the frontend site and input the api key, but when i click on "new quiz" i get this error. I am not sure what should i do. Thanks

![image](https://github.com/user-attachments/assets/d406f2c2-8ec7-4676-b0d3-1f815f3bd158)

**Comment by that-one-arab** [comment]
Did you make sure that you have started both the backend and the celery process?

**Comment by mattodinaturas** [comment]
hi, i haven't done it. There is no instructions about all this stuff in the readme

**Comment by that-one-arab** [comment]
Inside the backend readme, there is
